apiVersion: kubevirt.io/v1
kind: VirtualMachineInstanceReplicaSet
metadata:
  name: demo-vm-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      application: cnv-demo
  template:
    metadata:
      name: cnv-demo
      labels:
        application: cnv-demo
    spec:
      livenessProbe:
        initialDelaySeconds: 120
        periodSeconds: 5
        httpGet:
          port: 80
        timeoutSeconds: 3
      readinessProbe:
        httpGet:
          port: 80
        initialDelaySeconds: 120
        periodSeconds: 20
        timeoutSeconds: 3
        failureThreshold: 3
        successThreshold: 3
      domain:
        devices:
          interfaces:
          - name: nic0
            model: virtio
            masquerade: {}
          disks:
          - disk:
              bus: virtio
            name: containerdisk
            bootOrder: 1
          - disk:
              bus: virtio
            name: cloudinitdisk
          - disk: {}
            name: nginx-conf-disk
            serial: SX80KK
        resources:
          requests:
            cpu: 256m
            memory: 1G
      networks:
      - name: nic0
        pod: {}
      volumes:
      - name: containerdisk
        containerDisk:
          image: quay.io/kubevirt/fedora-cloud-container-disk-demo:v0.36.5
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: fedora
            chpasswd: { expire: False }
            bootcmd:
              # mount the ConfigMap
              - "mkdir /mnt/app-config"
              - "mount /dev/$(lsblk --nodeps -no name,serial | grep SX80KK | cut -f1 -d' ') /mnt/app-config"
            packages:
              - qemu-guest-agent
              - nginx
            package_update: true
            runcmd:
              #- dnf install qemu-guest-agent nginx -y
              - systemctl enable --now qemu-guest-agent
              - rm -f /etc/nginx/conf.d/*
              - cp /mnt/app-config/hello.conf /etc/nginx/conf.d/
              - cp /mnt/app-config/index.html /usr/share/nginx/html/
              - systemctl enable --now nginx
        name: cloudinitdisk
      - configMap:
          name: nginx-conf
        name: nginx-conf-disk
